framework:
    notifier:
        chatter_transports:
            firebase: '%env(FIREBASE_DSN)%'
            telegram: '%env(TELEGRAM_DSN)%'
        texter_transports:
            orange-sms: '%env(ORANGE_SMS_DSN)%'
            service-sms: '%env(SERVICE_SMS_DSN)%'
        channel_policy:
            # use chat/slack, chat/telegram, sms/twilio or sms/nexmo
            urgent: ['email', 'sms/service_sms', 'chat/telegram']
            high: ['email', 'sms/service_sms', 'chat/telegram']
            medium: ['email', 'chat/telegram']
            low: ['email', 'chat/telegram']
        admin_recipients:
            - { email: brice.mich@gmail.com }
