sonata_user:
    class:
        user: App\Entity\User
    resetting:
        email:
            address: brice.mich@gmail.com
            sender_name: Sonata Admin
    impersonating:
        route: sonata_admin_dashboard